CREATE DATABASE IF NOT EXISTS TODOAPP;

USE TODOAPP;

CREATE TABLE user (
    userId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE category (
    categoryId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    categoryName VARCHAR(150) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT ct_id_u_fk FOREIGN KEY (userId)
    REFERENCES user (userId)
);

CREATE TABLE task (
    taskId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    categoryId INT NOT NULL,
    taskName VARCHAR(150) NOT NULL,
    dueDate DATE,
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT tk_id_c_fk FOREIGN KEY (categoryId)
    REFERENCES category (categoryId)
);

CREATE TABLE activity (
    activityId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    taskId INT NOT NULL,
    assignedUser INT DEFAULT NULL,
    completed BOOLEAN DEFAULT FALSE,
    activityName VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT act_id_t_fk FOREIGN KEY (taskId)
    REFERENCES task (taskId),
    CONSTRAINT act_id_u_fk FOREIGN KEY (assignedUser)
    REFERENCES user (userId)
);
